/**
 * Comprehensive World Country Calling Dial Codes List (Alphabetical A-Z)
 */
export const COUNTRY_DIAL_CODES = [
  { code: '+93', name: 'Afghanistan', flag: '🇦🇫', display: '🇦🇫 Afghanistan (+93)' },
  { code: '+355', name: 'Albania', flag: '🇦🇱', display: '🇦🇱 Albania (+355)' },
  { code: '+213', name: 'Algeria', flag: '🇩🇿', display: '🇩🇿 Algeria (+213)' },
  { code: '+376', name: 'Andorra', flag: '🇦🇩', display: '🇦🇩 Andorra (+376)' },
  { code: '+244', name: 'Angola', flag: '🇦🇴', display: '🇦🇴 Angola (+244)' },
  { code: '+1-264', name: 'Anguilla', flag: '🇦🇮', display: '🇦🇮 Anguilla (+1-264)' },
  { code: '+1-268', name: 'Antigua and Barbuda', flag: '🇦🇬', display: '🇦🇬 Antigua and Barbuda (+1-268)' },
  { code: '+54', name: 'Argentina', flag: '🇦🇷', display: '🇦🇷 Argentina (+54)' },
  { code: '+374', name: 'Armenia', flag: '🇦🇲', display: '🇦🇲 Armenia (+374)' },
  { code: '+297', name: 'Aruba', flag: '🇦🇼', display: '🇦🇼 Aruba (+297)' },
  { code: '+61', name: 'Australia', flag: '🇦🇺', display: '🇦🇺 Australia (+61)' },
  { code: '+43', name: 'Austria', flag: '🇦🇹', display: '🇦🇹 Austria (+43)' },
  { code: '+994', name: 'Azerbaijan', flag: '🇦🇿', display: '🇦🇿 Azerbaijan (+994)' },
  { code: '+1-242', name: 'Bahamas', flag: '🇧🇸', display: '🇧🇸 Bahamas (+1-242)' },
  { code: '+973', name: 'Bahrain', flag: '🇧🇭', display: '🇧🇭 Bahrain (+973)' },
  { code: '+880', name: 'Bangladesh', flag: '🇧🇩', display: '🇧🇩 Bangladesh (+880)' },
  { code: '+1-246', name: 'Barbados', flag: '🇧🇧', display: '🇧🇧 Barbados (+1-246)' },
  { code: '+375', name: 'Belarus', flag: '🇧🇾', display: '🇧🇾 Belarus (+375)' },
  { code: '+32', name: 'Belgium', flag: '🇧🇪', display: '🇧🇪 Belgium (+32)' },
  { code: '+501', name: 'Belize', flag: '🇧🇿', display: '🇧🇿 Belize (+501)' },
  { code: '+229', name: 'Benin', flag: '🇧🇯', display: '🇧🇯 Benin (+229)' },
  { code: '+1-441', name: 'Bermuda', flag: '🇧🇲', display: '🇧🇲 Bermuda (+1-441)' },
  { code: '+975', name: 'Bhutan', flag: '🇧🇹', display: '🇧🇹 Bhutan (+975)' },
  { code: '+591', name: 'Bolivia', flag: '🇧🇴', display: '🇧🇴 Bolivia (+591)' },
  { code: '+387', name: 'Bosnia and Herzegovina', flag: '🇧🇦', display: '🇧🇦 Bosnia and Herzegovina (+387)' },
  { code: '+267', name: 'Botswana', flag: '🇧🇼', display: '🇧🇼 Botswana (+267)' },
  { code: '+55', name: 'Brazil', flag: '🇧🇷', display: '🇧🇷 Brazil (+55)' },
  { code: '+1-284', name: 'British Virgin Islands', flag: '🇻🇬', display: '🇻🇬 British Virgin Islands (+1-284)' },
  { code: '+673', name: 'Brunei', flag: '🇧🇳', display: '🇧🇳 Brunei (+673)' },
  { code: '+359', name: 'Bulgaria', flag: '🇧🇬', display: '🇧🇬 Bulgaria (+359)' },
  { code: '+226', name: 'Burkina Faso', flag: '🇧🇫', display: '🇧🇫 Burkina Faso (+226)' },
  { code: '+257', name: 'Burundi', flag: '🇧🇮', display: '🇧🇮 Burundi (+257)' },
  { code: '+855', name: 'Cambodia', flag: '🇰🇭', display: '🇰🇭 Cambodia (+855)' },
  { code: '+237', name: 'Cameroon', flag: '🇨🇲', display: '🇨🇲 Cameroon (+237)' },
  { code: '+1', name: 'Canada', flag: '🇨🇦', display: '🇨🇦 Canada (+1)' },
  { code: '+238', name: 'Cape Verde', flag: '🇨🇻', display: '🇨🇻 Cape Verde (+238)' },
  { code: '+1-345', name: 'Cayman Islands', flag: '🇰🇾', display: '🇰🇾 Cayman Islands (+1-345)' },
  { code: '+236', name: 'Central African Republic', flag: '🇨🇫', display: '🇨🇫 Central African Republic (+236)' },
  { code: '+235', name: 'Chad', flag: '🇹🇩', display: '🇹🇩 Chad (+235)' },
  { code: '+56', name: 'Chile', flag: '🇨🇱', display: '🇨🇱 Chile (+56)' },
  { code: '+86', name: 'China', flag: '🇨🇳', display: '🇨🇳 China (+86)' },
  { code: '+57', name: 'Colombia', flag: '🇨🇴', display: '🇨🇴 Colombia (+57)' },
  { code: '+269', name: 'Comoros', flag: '🇰🇲', display: '🇰🇲 Comoros (+269)' },
  { code: '+242', name: 'Congo (Brazzaville)', flag: '🇨🇬', display: '🇨🇬 Congo (+242)' },
  { code: '+243', name: 'Congo (DRC)', flag: '🇨🇩', display: '🇨🇩 Congo (DRC) (+243)' },
  { code: '+682', name: 'Cook Islands', flag: '🇨🇰', display: '🇨🇰 Cook Islands (+682)' },
  { code: '+506', name: 'Costa Rica', flag: '🇨🇷', display: '🇨🇷 Costa Rica (+506)' },
  { code: '+385', name: 'Croatia', flag: '🇭🇷', display: '🇭🇷 Croatia (+385)' },
  { code: '+53', name: 'Cuba', flag: '🇨🇺', display: '🇨🇺 Cuba (+53)' },
  { code: '+357', name: 'Cyprus', flag: '🇨🇾', display: '🇨🇾 Cyprus (+357)' },
  { code: '+420', name: 'Czech Republic', flag: '🇨🇿', display: '🇨🇿 Czech Republic (+420)' },
  { code: '+45', name: 'Denmark', flag: '🇩🇰', display: '🇩🇰 Denmark (+45)' },
  { code: '+253', name: 'Djibouti', flag: '🇩🇯', display: '🇩🇯 Djibouti (+253)' },
  { code: '+1-767', name: 'Dominica', flag: '🇩🇲', display: '🇩🇲 Dominica (+1-767)' },
  { code: '+1-809', name: 'Dominican Republic', flag: '🇩🇴', display: '🇩🇴 Dominican Republic (+1-809)' },
  { code: '+593', name: 'Ecuador', flag: '🇪🇨', display: '🇪🇨 Ecuador (+593)' },
  { code: '+20', name: 'Egypt', flag: '🇪🇬', display: '🇪🇬 Egypt (+20)' },
  { code: '+503', name: 'El Salvador', flag: '🇸🇻', display: '🇸🇻 El Salvador (+503)' },
  { code: '+240', name: 'Equatorial Guinea', flag: '🇬🇶', display: '🇬🇶 Equatorial Guinea (+240)' },
  { code: '+291', name: 'Eritrea', flag: '🇪🇷', display: '🇪🇷 Eritrea (+291)' },
  { code: '+372', name: 'Estonia', flag: '🇪🇪', display: '🇪🇪 Estonia (+372)' },
  { code: '+268', name: 'Eswatini', flag: '🇸🇿', display: '🇸🇿 Eswatini (+268)' },
  { code: '+251', name: 'Ethiopia', flag: '🇪🇹', display: '🇪🇹 Ethiopia (+251)' },
  { code: '+679', name: 'Fiji', flag: '🇫🇯', display: '🇫🇯 Fiji (+679)' },
  { code: '+358', name: 'Finland', flag: '🇫🇮', display: '🇫🇮 Finland (+358)' },
  { code: '+33', name: 'France', flag: '🇫🇷', display: '🇫🇷 France (+33)' },
  { code: '+241', name: 'Gabon', flag: '🇬🇦', display: '🇬🇦 Gabon (+241)' },
  { code: '+220', name: 'Gambia', flag: '🇬🇲', display: '🇬🇲 Gambia (+220)' },
  { code: '+995', name: 'Georgia', flag: '🇬🇪', display: '🇬🇪 Georgia (+995)' },
  { code: '+49', name: 'Germany', flag: '🇩🇪', display: '🇩🇪 Germany (+49)' },
  { code: '+233', name: 'Ghana', flag: '🇬🇭', display: '🇬🇭 Ghana (+233)' },
  { code: '+30', name: 'Greece', flag: '🇬🇷', display: '🇬🇷 Greece (+30)' },
  { code: '+299', name: 'Greenland', flag: '🇬🇱', display: '🇬🇱 Greenland (+299)' },
  { code: '+1-473', name: 'Grenada', flag: '🇬🇩', display: '🇬🇩 Grenada (+1-473)' },
  { code: '+502', name: 'Guatemala', flag: '🇬🇹', display: '🇬🇹 Guatemala (+502)' },
  { code: '+224', name: 'Guinea', flag: '🇬🇳', display: '🇬🇳 Guinea (+224)' },
  { code: '+245', name: 'Guinea-Bissau', flag: '🇬🇼', display: '🇬🇼 Guinea-Bissau (+245)' },
  { code: '+592', name: 'Guyana', flag: '🇬🇾', display: '🇬🇾 Guyana (+592)' },
  { code: '+509', name: 'Haiti', flag: '🇭🇹', display: '🇭🇹 Haiti (+509)' },
  { code: '+504', name: 'Honduras', flag: '🇭🇳', display: '🇭🇳 Honduras (+504)' },
  { code: '+852', name: 'Hong Kong', flag: '🇭🇰', display: '🇭🇰 Hong Kong (+852)' },
  { code: '+36', name: 'Hungary', flag: '🇭🇺', display: '🇭🇺 Hungary (+36)' },
  { code: '+354', name: 'Iceland', flag: '🇮🇸', display: '🇮🇸 Iceland (+354)' },
  { code: '+91', name: 'India', flag: '🇮🇳', display: '🇮🇳 India (+91)' },
  { code: '+62', name: 'Indonesia', flag: '🇮🇩', display: '🇮🇩 Indonesia (+62)' },
  { code: '+98', name: 'Iran', flag: '🇮🇷', display: '🇮🇷 Iran (+98)' },
  { code: '+964', name: 'Iraq', flag: '🇮🇶', display: '🇮🇶 Iraq (+964)' },
  { code: '+353', name: 'Ireland', flag: '🇮🇪', display: '🇮🇪 Ireland (+353)' },
  { code: '+972', name: 'Israel', flag: '🇮🇱', display: '🇮🇱 Israel (+972)' },
  { code: '+39', name: 'Italy', flag: '🇮🇹', display: '🇮🇹 Italy (+39)' },
  { code: '+225', name: 'Ivory Coast', flag: '🇨🇮', display: '🇨🇮 Ivory Coast (+225)' },
  { code: '+1-876', name: 'Jamaica', flag: '🇯🇲', display: '🇯🇲 Jamaica (+1-876)' },
  { code: '+81', name: 'Japan', flag: '🇯🇵', display: '🇯🇵 Japan (+81)' },
  { code: '+962', name: 'Jordan', flag: '🇯🇴', display: '🇯🇴 Jordan (+962)' },
  { code: '+7', name: 'Kazakhstan', flag: '🇰🇿', display: '🇰🇿 Kazakhstan (+7)' },
  { code: '+254', name: 'Kenya', flag: '🇰🇪', display: '🇰🇪 Kenya (+254)' },
  { code: '+686', name: 'Kiribati', flag: '🇰🇮', display: '🇰🇮 Kiribati (+686)' },
  { code: '+965', name: 'Kuwait', flag: '🇰🇼', display: '🇰🇼 Kuwait (+965)' },
  { code: '+996', name: 'Kyrgyzstan', flag: '🇰🇬', display: '🇰🇬 Kyrgyzstan (+996)' },
  { code: '+856', name: 'Laos', flag: '🇱🇦', display: '🇱🇦 Laos (+856)' },
  { code: '+371', name: 'Latvia', flag: '🇱🇻', display: '🇱🇻 Latvia (+371)' },
  { code: '+961', name: 'Lebanon', flag: '🇱🇧', display: '🇱🇧 Lebanon (+961)' },
  { code: '+266', name: 'Lesotho', flag: '🇱🇸', display: '🇱🇸 Lesotho (+266)' },
  { code: '+231', name: 'Liberia', flag: '🇱🇷', display: '🇱🇷 Liberia (+231)' },
  { code: '+218', name: 'Libya', flag: '🇱🇾', display: '🇱🇾 Libya (+218)' },
  { code: '+423', name: 'Liechtenstein', flag: '🇱🇮', display: '🇱🇮 Liechtenstein (+423)' },
  { code: '+370', name: 'Lithuania', flag: '🇱🇹', display: '🇱🇹 Lithuania (+370)' },
  { code: '+352', name: 'Luxembourg', flag: '🇱🇺', display: '🇱🇺 Luxembourg (+352)' },
  { code: '+853', name: 'Macau', flag: '🇲🇴', display: '🇲🇴 Macau (+853)' },
  { code: '+389', name: 'North Macedonia', flag: '🇲🇰', display: '🇲🇰 North Macedonia (+389)' },
  { code: '+261', name: 'Madagascar', flag: '🇲🇬', display: '🇲🇬 Madagascar (+261)' },
  { code: '+265', name: 'Malawi', flag: '🇲🇼', display: '🇲🇼 Malawi (+265)' },
  { code: '+60', name: 'Malaysia', flag: '🇲🇾', display: '🇲🇾 Malaysia (+60)' },
  { code: '+960', name: 'Maldives', flag: '🇲🇻', display: '🇲🇻 Maldives (+960)' },
  { code: '+223', name: 'Mali', flag: '🇲🇱', display: '🇲🇱 Mali (+223)' },
  { code: '+356', name: 'Malta', flag: '🇲🇹', display: '🇲🇹 Malta (+356)' },
  { code: '+692', name: 'Marshall Islands', flag: '🇲🇭', display: '🇲🇭 Marshall Islands (+692)' },
  { code: '+222', name: 'Mauritania', flag: '🇲🇷', display: '🇲🇷 Mauritania (+222)' },
  { code: '+230', name: 'Mauritius', flag: '🇲🇺', display: '🇲🇺 Mauritius (+230)' },
  { code: '+52', name: 'Mexico', flag: '🇲🇽', display: '🇲🇽 Mexico (+52)' },
  { code: '+691', name: 'Micronesia', flag: '🇫🇲', display: '🇫🇲 Micronesia (+691)' },
  { code: '+373', name: 'Moldova', flag: '🇲🇩', display: '🇲🇩 Moldova (+373)' },
  { code: '+377', name: 'Monaco', flag: '🇲🇨', display: '🇲🇨 Monaco (+377)' },
  { code: '+976', name: 'Mongolia', flag: '🇲🇳', display: '🇲🇳 Mongolia (+976)' },
  { code: '+382', name: 'Montenegro', flag: '🇲🇪', display: '🇲🇪 Montenegro (+382)' },
  { code: '+1-664', name: 'Montserrat', flag: '🇲🇸', display: '🇲🇸 Montserrat (+1-664)' },
  { code: '+212', name: 'Morocco', flag: '🇲🇦', display: '🇲🇦 Morocco (+212)' },
  { code: '+258', name: 'Mozambique', flag: '🇲🇿', display: '🇲🇿 Mozambique (+258)' },
  { code: '+95', name: 'Myanmar', flag: '🇲🇲', display: '🇲🇲 Myanmar (+95)' },
  { code: '+264', name: 'Namibia', flag: '🇳🇦', display: '🇳🇦 Namibia (+264)' },
  { code: '+674', name: 'Nauru', flag: '🇳🇷', display: '🇳🇷 Nauru (+674)' },
  { code: '+977', name: 'Nepal', flag: '🇳🇵', display: '🇳🇵 Nepal (+977)' },
  { code: '+31', name: 'Netherlands', flag: '🇳🇱', display: '🇳🇱 Netherlands (+31)' },
  { code: '+64', name: 'New Zealand', flag: '🇳🇿', display: '🇳🇿 New Zealand (+64)' },
  { code: '+505', name: 'Nicaragua', flag: '🇳🇮', display: '🇳🇮 Nicaragua (+505)' },
  { code: '+227', name: 'Niger', flag: '🇳🇪', display: '🇳🇪 Niger (+227)' },
  { code: '+234', name: 'Nigeria', flag: '🇳🇬', display: '🇳🇬 Nigeria (+234)' },
  { code: '+47', name: 'Norway', flag: '🇳🇴', display: '🇳🇴 Norway (+47)' },
  { code: '+968', name: 'Oman', flag: '🇴🇲', display: '🇴🇲 Oman (+968)' },
  { code: '+92', name: 'Pakistan', flag: '🇵🇰', display: '🇵🇰 Pakistan (+92)' },
  { code: '+680', name: 'Palau', flag: '🇵🇼', display: '🇵🇼 Palau (+680)' },
  { code: '+970', name: 'Palestine', flag: '🇵🇸', display: '🇵🇸 Palestine (+970)' },
  { code: '+507', name: 'Panama', flag: '🇵🇦', display: '🇵🇦 Panama (+507)' },
  { code: '+675', name: 'Papua New Guinea', flag: '🇵🇬', display: '🇵🇬 Papua New Guinea (+675)' },
  { code: '+595', name: 'Paraguay', flag: '🇵🇾', display: '🇵🇾 Paraguay (+595)' },
  { code: '+51', name: 'Peru', flag: '🇵🇪', display: '🇵🇪 Peru (+51)' },
  { code: '+63', name: 'Philippines', flag: '🇵🇭', display: '🇵🇭 Philippines (+63)' },
  { code: '+48', name: 'Poland', flag: '🇵🇱', display: '🇵🇱 Poland (+48)' },
  { code: '+351', name: 'Portugal', flag: '🇵🇹', display: '🇵🇹 Portugal (+351)' },
  { code: '+1-787', name: 'Puerto Rico', flag: '🇵🇷', display: '🇵🇷 Puerto Rico (+1-787)' },
  { code: '+974', name: 'Qatar', flag: '🇶🇦', display: '🇶🇦 Qatar (+974)' },
  { code: '+40', name: 'Romania', flag: '🇷🇴', display: '🇷🇴 Romania (+40)' },
  { code: '+7', name: 'Russia', flag: '🇷🇺', display: '🇷🇺 Russia (+7)' },
  { code: '+250', name: 'Rwanda', flag: '🇷🇼', display: '🇷🇼 Rwanda (+250)' },
  { code: '+1-869', name: 'Saint Kitts and Nevis', flag: '🇰🇳', display: '🇰🇳 Saint Kitts and Nevis (+1-869)' },
  { code: '+1-758', name: 'Saint Lucia', flag: '🇱🇨', display: '🇱🇨 Saint Lucia (+1-758)' },
  { code: '+1-784', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨', display: '🇻🇨 Saint Vincent (+1-784)' },
  { code: '+685', name: 'Samoa', flag: '🇼🇸', display: '🇼🇸 Samoa (+685)' },
  { code: '+378', name: 'San Marino', flag: '🇸🇲', display: '🇸🇲 San Marino (+378)' },
  { code: '+239', name: 'Sao Tome and Principe', flag: '🇸🇹', display: '🇸🇹 Sao Tome and Principe (+239)' },
  { code: '+966', name: 'Saudi Arabia', flag: '🇸🇦', display: '🇸🇦 Saudi Arabia (+966)' },
  { code: '+221', name: 'Senegal', flag: '🇸🇳', display: '🇸🇳 Senegal (+221)' },
  { code: '+381', name: 'Serbia', flag: '🇷🇸', display: '🇷🇸 Serbia (+381)' },
  { code: '+248', name: 'Seychelles', flag: '🇸🇨', display: '🇸🇨 Seychelles (+248)' },
  { code: '+232', name: 'Sierra Leone', flag: '🇸🇱', display: '🇸🇱 Sierra Leone (+232)' },
  { code: '+65', name: 'Singapore', flag: '🇸🇬', display: '🇸🇬 Singapore (+65)' },
  { code: '+421', name: 'Slovakia', flag: '🇸🇰', display: '🇸🇰 Slovakia (+421)' },
  { code: '+386', name: 'Slovenia', flag: '🇸🇮', display: '🇸🇮 Slovenia (+386)' },
  { code: '+677', name: 'Solomon Islands', flag: '🇸🇧', display: '🇸🇧 Solomon Islands (+677)' },
  { code: '+252', name: 'Somalia', flag: '🇸🇴', display: '🇸🇴 Somalia (+252)' },
  { code: '+27', name: 'South Africa', flag: '🇿🇦', display: '🇿🇦 South Africa (+27)' },
  { code: '+82', name: 'South Korea', flag: '🇰🇷', display: '🇰🇷 South Korea (+82)' },
  { code: '+211', name: 'South Sudan', flag: '🇸🇸', display: '🇸🇸 South Sudan (+211)' },
  { code: '+34', name: 'Spain', flag: '🇪🇸', display: '🇪🇸 Spain (+34)' },
  { code: '+94', name: 'Sri Lanka', flag: '🇱🇰', display: '🇱🇰 Sri Lanka (+94)' },
  { code: '+249', name: 'Sudan', flag: '🇸🇩', display: '🇸🇩 Sudan (+249)' },
  { code: '+597', name: 'Suriname', flag: '🇸🇷', display: '🇸🇷 Suriname (+597)' },
  { code: '+46', name: 'Sweden', flag: '🇸🇪', display: '🇸🇪 Sweden (+46)' },
  { code: '+41', name: 'Switzerland', flag: '🇨🇭', display: '🇨🇭 Switzerland (+41)' },
  { code: '+963', name: 'Syria', flag: '🇸🇾', display: '🇸🇾 Syria (+963)' },
  { code: '+886', name: 'Taiwan', flag: '🇹🇼', display: '🇹🇼 Taiwan (+886)' },
  { code: '+992', name: 'Tajikistan', flag: '🇹🇯', display: '🇹🇯 Tajikistan (+992)' },
  { code: '+255', name: 'Tanzania', flag: '🇹🇿', display: '🇹🇿 Tanzania (+255)' },
  { code: '+66', name: 'Thailand', flag: '🇹🇭', display: '🇹🇭 Thailand (+66)' },
  { code: '+670', name: 'Timor-Leste', flag: '🇹🇱', display: '🇹🇱 Timor-Leste (+670)' },
  { code: '+228', name: 'Togo', flag: '🇹🇬', display: '🇹🇬 Togo (+228)' },
  { code: '+676', name: 'Tonga', flag: '🇹🇴', display: '🇹🇴 Tonga (+676)' },
  { code: '+1-868', name: 'Trinidad and Tobago', flag: '🇹🇹', display: '🇹🇹 Trinidad and Tobago (+1-868)' },
  { code: '+216', name: 'Tunisia', flag: '🇹🇳', display: '🇹🇳 Tunisia (+216)' },
  { code: '+90', name: 'Turkey', flag: '🇹🇷', display: '🇹🇷 Turkey (+90)' },
  { code: '+993', name: 'Turkmenistan', flag: '🇹🇲', display: '🇹🇲 Turkmenistan (+993)' },
  { code: '+1-649', name: 'Turks and Caicos Islands', flag: '🇹🇨', display: '🇹🇨 Turks and Caicos (+1-649)' },
  { code: '+688', name: 'Tuvalu', flag: '🇹🇻', display: '🇹🇻 Tuvalu (+688)' },
  { code: '+256', name: 'Uganda', flag: '🇺🇬', display: '🇺🇬 Uganda (+256)' },
  { code: '+380', name: 'Ukraine', flag: '🇺🇦', display: '🇺🇦 Ukraine (+380)' },
  { code: '+971', name: 'United Arab Emirates', flag: '🇦🇪', display: '🇦🇪 UAE (+971)' },
  { code: '+44', name: 'United Kingdom', flag: '🇬🇧', display: '🇬🇧 UK (+44)' },
  { code: '+1', name: 'United States', flag: '🇺🇸', display: '🇺🇸 USA (+1)' },
  { code: '+598', name: 'Uruguay', flag: '🇺🇾', display: '🇺🇾 Uruguay (+598)' },
  { code: '+998', name: 'Uzbekistan', flag: '🇺🇿', display: '🇺🇿 Uzbekistan (+998)' },
  { code: '+678', name: 'Vanuatu', flag: '🇻🇺', display: '🇻🇺 Vanuatu (+678)' },
  { code: '+379', name: 'Vatican City', flag: '🇻🇦', display: '🇻🇦 Vatican City (+379)' },
  { code: '+58', name: 'Venezuela', flag: '🇻🇪', display: '🇻🇪 Venezuela (+58)' },
  { code: '+84', name: 'Vietnam', flag: '🇻🇳', display: '🇻🇳 Vietnam (+84)' },
  { code: '+967', name: 'Yemen', flag: '🇾🇪', display: '🇾🇪 Yemen (+967)' },
  { code: '+260', name: 'Zambia', flag: '🇿🇲', display: '🇿🇲 Zambia (+260)' },
  { code: '+263', name: 'Zimbabwe', flag: '🇿🇼', display: '🇿🇼 Zimbabwe (+263)' }
];
